Deployment error => import path changed to absolute for NavBar component
RollupError: Could not resolve "./components/NavBar/NavBar" from "src/App.jsx"